#!/bin/sh

 echo "Usage:"
 echo "PrimeCloud Controller User Mnanagement Tool"
 echo "Options:"
 echo "ユーザ一覧"
 echo "#./pcc-show-user.sh"
 echo "プラットフォーム一覧"
 echo "#./pcc-show-platform.sh"
 echo "PCCのユーザ作成:"
 echo "#./pcc-add-user.sh -u <ユーザ名> -p <パスワード>"
 echo "ユーザの無効化"
 echo "#./pcc-disable-user.sh -u <ユーザ名>"
 echo "ユーザの有効化"
 echo "#./pcc-enable-user.sh -u <ユーザ名>"
 echo "ユーザへのEC2プラットフォーム追加"
 echo "#./pcc-enable-user-aws.sh -u <追加したいユーザ名> -P <プラットフォーム名>"
 echo "ユーザへのVMwareプラットフォーム追加"
 echo "#./pcc-enable-user-vmware.sh -u <追加したいユーザ名> -P <プラットフォーム名>"
 echo "ユーザのパスワード変更"
 echo "#./pcc-modify-user.sh -u <変更したいユーザ名> -p <新パスワード>"
 echo "設定の確認"
 echo "#./pcc-check-config.sh"

