
package jp.primecloud.auto.nifty.soap.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NiftyCloud", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", wsdlLocation = "classpath:/NiftyCloud.wsdl")
public class NiftyCloud
    extends Service
{

    private final static URL NIFTYCLOUD_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jp.primecloud.auto.nifty.soap.jaxws.NiftyCloud.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jp.primecloud.auto.nifty.soap.jaxws.NiftyCloud.class.getResource(".");
            url = new URL(baseUrl, "classpath:/NiftyCloud.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'classpath:/NiftyCloud.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NIFTYCLOUD_WSDL_LOCATION = url;
    }

    public NiftyCloud(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NiftyCloud() {
        super(NIFTYCLOUD_WSDL_LOCATION, new QName("https://cp.cloud.nifty.com/api/1.3/", "NiftyCloud"));
    }

    /**
     * 
     * @return
     *     returns NiftyCloudPortType
     */
    @WebEndpoint(name = "NiftyCloudPort")
    public NiftyCloudPortType getNiftyCloudPort() {
        return super.getPort(new QName("https://cp.cloud.nifty.com/api/1.3/", "NiftyCloudPort"), NiftyCloudPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NiftyCloudPortType
     */
    @WebEndpoint(name = "NiftyCloudPort")
    public NiftyCloudPortType getNiftyCloudPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://cp.cloud.nifty.com/api/1.3/", "NiftyCloudPort"), NiftyCloudPortType.class, features);
    }

}
