
package jp.primecloud.auto.nifty.soap.jaxws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NiftyCloudPortType", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NiftyCloudPortType {


    /**
     * 
     * @param describeInstanceAttributeRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DescribeInstanceAttributeResponseType>
     */
    @WebMethod(operationName = "DescribeInstanceAttribute", action = "DescribeInstanceAttribute")
    public Response<DescribeInstanceAttributeResponseType> describeInstanceAttributeAsync(
        @WebParam(name = "DescribeInstanceAttribute", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstanceAttributeRequestMsgReq")
        DescribeInstanceAttributeType describeInstanceAttributeRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param describeInstanceAttributeRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DescribeInstanceAttribute", action = "DescribeInstanceAttribute")
    public Future<?> describeInstanceAttributeAsync(
        @WebParam(name = "DescribeInstanceAttribute", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstanceAttributeRequestMsgReq")
        DescribeInstanceAttributeType describeInstanceAttributeRequestMsgReq,
        @WebParam(name = "DescribeInstanceAttributeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DescribeInstanceAttributeResponseType> asyncHandler);

    /**
     * 
     * @param describeInstanceAttributeRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DescribeInstanceAttributeResponseType
     */
    @WebMethod(operationName = "DescribeInstanceAttribute", action = "DescribeInstanceAttribute")
    @WebResult(name = "DescribeInstanceAttributeResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstanceAttributeRequestMsgResp")
    public DescribeInstanceAttributeResponseType describeInstanceAttribute(
        @WebParam(name = "DescribeInstanceAttribute", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstanceAttributeRequestMsgReq")
        DescribeInstanceAttributeType describeInstanceAttributeRequestMsgReq);

    /**
     * 
     * @param describeInstancesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DescribeInstancesResponseType>
     */
    @WebMethod(operationName = "DescribeInstances", action = "DescribeInstances")
    public Response<DescribeInstancesResponseType> describeInstancesAsync(
        @WebParam(name = "DescribeInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstancesRequestMsgReq")
        DescribeInstancesType describeInstancesRequestMsgReq);

    /**
     * 
     * @param describeInstancesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DescribeInstances", action = "DescribeInstances")
    public Future<?> describeInstancesAsync(
        @WebParam(name = "DescribeInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstancesRequestMsgReq")
        DescribeInstancesType describeInstancesRequestMsgReq,
        @WebParam(name = "DescribeInstancesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DescribeInstancesResponseType> asyncHandler);

    /**
     * 
     * @param describeInstancesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DescribeInstancesResponseType
     */
    @WebMethod(operationName = "DescribeInstances", action = "DescribeInstances")
    @WebResult(name = "DescribeInstancesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstancesRequestMsgResp")
    public DescribeInstancesResponseType describeInstances(
        @WebParam(name = "DescribeInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeInstancesRequestMsgReq")
        DescribeInstancesType describeInstancesRequestMsgReq);

    /**
     * 
     * @param modifyInstanceAttributeRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.ModifyInstanceAttributeResponseType>
     */
    @WebMethod(operationName = "ModifyInstanceAttribute", action = "ModifyInstanceAttribute")
    public Response<ModifyInstanceAttributeResponseType> modifyInstanceAttributeAsync(
        @WebParam(name = "ModifyInstanceAttribute", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "ModifyInstanceAttributeRequestMsgReq")
        ModifyInstanceAttributeType modifyInstanceAttributeRequestMsgReq);

    /**
     * 
     * @param modifyInstanceAttributeRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ModifyInstanceAttribute", action = "ModifyInstanceAttribute")
    public Future<?> modifyInstanceAttributeAsync(
        @WebParam(name = "ModifyInstanceAttribute", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "ModifyInstanceAttributeRequestMsgReq")
        ModifyInstanceAttributeType modifyInstanceAttributeRequestMsgReq,
        @WebParam(name = "ModifyInstanceAttributeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ModifyInstanceAttributeResponseType> asyncHandler);

    /**
     * 
     * @param modifyInstanceAttributeRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.ModifyInstanceAttributeResponseType
     */
    @WebMethod(operationName = "ModifyInstanceAttribute", action = "ModifyInstanceAttribute")
    @WebResult(name = "ModifyInstanceAttributeResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "ModifyInstanceAttributeRequestMsgResp")
    public ModifyInstanceAttributeResponseType modifyInstanceAttribute(
        @WebParam(name = "ModifyInstanceAttribute", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "ModifyInstanceAttributeRequestMsgReq")
        ModifyInstanceAttributeType modifyInstanceAttributeRequestMsgReq);

    /**
     * 
     * @param rebootInstancesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.RebootInstancesResponseType>
     */
    @WebMethod(operationName = "RebootInstances", action = "RebootInstances")
    public Response<RebootInstancesResponseType> rebootInstancesAsync(
        @WebParam(name = "RebootInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RebootInstancesRequestMsgReq")
        RebootInstancesType rebootInstancesRequestMsgReq);

    /**
     * 
     * @param rebootInstancesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RebootInstances", action = "RebootInstances")
    public Future<?> rebootInstancesAsync(
        @WebParam(name = "RebootInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RebootInstancesRequestMsgReq")
        RebootInstancesType rebootInstancesRequestMsgReq,
        @WebParam(name = "RebootInstancesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RebootInstancesResponseType> asyncHandler);

    /**
     * 
     * @param rebootInstancesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.RebootInstancesResponseType
     */
    @WebMethod(operationName = "RebootInstances", action = "RebootInstances")
    @WebResult(name = "RebootInstancesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RebootInstancesRequestMsgResp")
    public RebootInstancesResponseType rebootInstances(
        @WebParam(name = "RebootInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RebootInstancesRequestMsgReq")
        RebootInstancesType rebootInstancesRequestMsgReq);

    /**
     * 
     * @param runInstancesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.RunInstancesResponseType>
     */
    @WebMethod(operationName = "RunInstances", action = "RunInstances")
    public Response<RunInstancesResponseType> runInstancesAsync(
        @WebParam(name = "RunInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RunInstancesRequestMsgReq")
        RunInstancesType runInstancesRequestMsgReq);

    /**
     * 
     * @param runInstancesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "RunInstances", action = "RunInstances")
    public Future<?> runInstancesAsync(
        @WebParam(name = "RunInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RunInstancesRequestMsgReq")
        RunInstancesType runInstancesRequestMsgReq,
        @WebParam(name = "RunInstancesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<RunInstancesResponseType> asyncHandler);

    /**
     * 
     * @param runInstancesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.RunInstancesResponseType
     */
    @WebMethod(operationName = "RunInstances", action = "RunInstances")
    @WebResult(name = "RunInstancesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RunInstancesResponseMsgResp")
    public RunInstancesResponseType runInstances(
        @WebParam(name = "RunInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "RunInstancesRequestMsgReq")
        RunInstancesType runInstancesRequestMsgReq);

    /**
     * 
     * @param startInstancesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.StartInstancesResponseType>
     */
    @WebMethod(operationName = "StartInstances", action = "StartInstances")
    public Response<StartInstancesResponseType> startInstancesAsync(
        @WebParam(name = "StartInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StartInstancesRequestMsgReq")
        StartInstancesType startInstancesRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param startInstancesRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "StartInstances", action = "StartInstances")
    public Future<?> startInstancesAsync(
        @WebParam(name = "StartInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StartInstancesRequestMsgReq")
        StartInstancesType startInstancesRequestMsgReq,
        @WebParam(name = "StartInstancesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<StartInstancesResponseType> asyncHandler);

    /**
     * 
     * @param startInstancesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.StartInstancesResponseType
     */
    @WebMethod(operationName = "StartInstances", action = "StartInstances")
    @WebResult(name = "StartInstancesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StartInstancesResponseMsgResp")
    public StartInstancesResponseType startInstances(
        @WebParam(name = "StartInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StartInstancesRequestMsgReq")
        StartInstancesType startInstancesRequestMsgReq);

    /**
     * 
     * @param stopInstancesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.StopInstancesResponseType>
     */
    @WebMethod(operationName = "StopInstances", action = "StopInstances")
    public Response<StopInstancesResponseType> stopInstancesAsync(
        @WebParam(name = "StopInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StopInstancesRequestMsgReq")
        StopInstancesType stopInstancesRequestMsgReq);

    /**
     * 
     * @param stopInstancesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "StopInstances", action = "StopInstances")
    public Future<?> stopInstancesAsync(
        @WebParam(name = "StopInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StopInstancesRequestMsgReq")
        StopInstancesType stopInstancesRequestMsgReq,
        @WebParam(name = "StopInstancesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<StopInstancesResponseType> asyncHandler);

    /**
     * 
     * @param stopInstancesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.StopInstancesResponseType
     */
    @WebMethod(operationName = "StopInstances", action = "StopInstances")
    @WebResult(name = "StopInstancesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StopInstancesResponseMsgResp")
    public StopInstancesResponseType stopInstances(
        @WebParam(name = "StopInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "StopInstancesRequestMsgReq")
        StopInstancesType stopInstancesRequestMsgReq);

    /**
     * 
     * @param terminateInstancesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.TerminateInstancesResponseType>
     */
    @WebMethod(operationName = "TerminateInstances", action = "TerminateInstances")
    public Response<TerminateInstancesResponseType> terminateInstancesAsync(
        @WebParam(name = "TerminateInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "TerminateInstancesRequestMsgReq")
        TerminateInstancesType terminateInstancesRequestMsgReq);

    /**
     * 
     * @param terminateInstancesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "TerminateInstances", action = "TerminateInstances")
    public Future<?> terminateInstancesAsync(
        @WebParam(name = "TerminateInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "TerminateInstancesRequestMsgReq")
        TerminateInstancesType terminateInstancesRequestMsgReq,
        @WebParam(name = "TerminateInstancesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<TerminateInstancesResponseType> asyncHandler);

    /**
     * 
     * @param terminateInstancesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.TerminateInstancesResponseType
     */
    @WebMethod(operationName = "TerminateInstances", action = "TerminateInstances")
    @WebResult(name = "TerminateInstancesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "TerminateInstancesResponseMsgResp")
    public TerminateInstancesResponseType terminateInstances(
        @WebParam(name = "TerminateInstances", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "TerminateInstancesRequestMsgReq")
        TerminateInstancesType terminateInstancesRequestMsgReq);

    /**
     * 
     * @param attachVolumeRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.AttachVolumeResponseType>
     */
    @WebMethod(operationName = "AttachVolume", action = "AttachVolume")
    public Response<AttachVolumeResponseType> attachVolumeAsync(
        @WebParam(name = "AttachVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "AttachVolumeRequestMsgReq")
        AttachVolumeType attachVolumeRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param attachVolumeRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "AttachVolume", action = "AttachVolume")
    public Future<?> attachVolumeAsync(
        @WebParam(name = "AttachVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "AttachVolumeRequestMsgReq")
        AttachVolumeType attachVolumeRequestMsgReq,
        @WebParam(name = "AttachVolumeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AttachVolumeResponseType> asyncHandler);

    /**
     * 
     * @param attachVolumeRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.AttachVolumeResponseType
     */
    @WebMethod(operationName = "AttachVolume", action = "AttachVolume")
    @WebResult(name = "AttachVolumeResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "AttachVolumeResponseMsgResp")
    public AttachVolumeResponseType attachVolume(
        @WebParam(name = "AttachVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "AttachVolumeRequestMsgReq")
        AttachVolumeType attachVolumeRequestMsgReq);

    /**
     * 
     * @param createVolumeRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.CreateVolumeResponseType>
     */
    @WebMethod(operationName = "CreateVolume", action = "CreateVolume")
    public Response<CreateVolumeResponseType> createVolumeAsync(
        @WebParam(name = "CreateVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateVolumeRequestMsgReq")
        CreateVolumeType createVolumeRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param createVolumeRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CreateVolume", action = "CreateVolume")
    public Future<?> createVolumeAsync(
        @WebParam(name = "CreateVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateVolumeRequestMsgReq")
        CreateVolumeType createVolumeRequestMsgReq,
        @WebParam(name = "CreateVolumeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CreateVolumeResponseType> asyncHandler);

    /**
     * 
     * @param createVolumeRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.CreateVolumeResponseType
     */
    @WebMethod(operationName = "CreateVolume", action = "CreateVolume")
    @WebResult(name = "CreateVolumeResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateVolumeRequestMsgResp")
    public CreateVolumeResponseType createVolume(
        @WebParam(name = "CreateVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateVolumeRequestMsgReq")
        CreateVolumeType createVolumeRequestMsgReq);

    /**
     * 
     * @param deleteVolumeRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DeleteVolumeResponseType>
     */
    @WebMethod(operationName = "DeleteVolume", action = "DeleteVolume")
    public Response<DeleteVolumeResponseType> deleteVolumeAsync(
        @WebParam(name = "DeleteVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteVolumeRequestMsgReq")
        DeleteVolumeType deleteVolumeRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param deleteVolumeRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteVolume", action = "DeleteVolume")
    public Future<?> deleteVolumeAsync(
        @WebParam(name = "DeleteVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteVolumeRequestMsgReq")
        DeleteVolumeType deleteVolumeRequestMsgReq,
        @WebParam(name = "DeleteVolumeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteVolumeResponseType> asyncHandler);

    /**
     * 
     * @param deleteVolumeRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DeleteVolumeResponseType
     */
    @WebMethod(operationName = "DeleteVolume", action = "DeleteVolume")
    @WebResult(name = "DeleteVolumeResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteVolumeRequestMsgResp")
    public DeleteVolumeResponseType deleteVolume(
        @WebParam(name = "DeleteVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteVolumeRequestMsgReq")
        DeleteVolumeType deleteVolumeRequestMsgReq);

    /**
     * 
     * @param describeVolumesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DescribeVolumesResponseType>
     */
    @WebMethod(operationName = "DescribeVolumes", action = "DescribeVolumes")
    public Response<DescribeVolumesResponseType> describeVolumesAsync(
        @WebParam(name = "DescribeVolumes", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeVolumesRequestMsgReq")
        DescribeVolumesType describeVolumesRequestMsgReq);

    /**
     * 
     * @param describeVolumesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DescribeVolumes", action = "DescribeVolumes")
    public Future<?> describeVolumesAsync(
        @WebParam(name = "DescribeVolumes", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeVolumesRequestMsgReq")
        DescribeVolumesType describeVolumesRequestMsgReq,
        @WebParam(name = "DescribeVolumesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DescribeVolumesResponseType> asyncHandler);

    /**
     * 
     * @param describeVolumesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DescribeVolumesResponseType
     */
    @WebMethod(operationName = "DescribeVolumes", action = "DescribeVolumes")
    @WebResult(name = "DescribeVolumesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeVolumesRequestMsgResp")
    public DescribeVolumesResponseType describeVolumes(
        @WebParam(name = "DescribeVolumes", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeVolumesRequestMsgReq")
        DescribeVolumesType describeVolumesRequestMsgReq);

    /**
     * 
     * @param detachVolumeRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DetachVolumeResponseType>
     */
    @WebMethod(operationName = "DetachVolume", action = "DetachVolume")
    public Response<DetachVolumeResponseType> detachVolumeAsync(
        @WebParam(name = "DetachVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DetachVolumeRequestMsgReq")
        DetachVolumeType detachVolumeRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param detachVolumeRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DetachVolume", action = "DetachVolume")
    public Future<?> detachVolumeAsync(
        @WebParam(name = "DetachVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DetachVolumeRequestMsgReq")
        DetachVolumeType detachVolumeRequestMsgReq,
        @WebParam(name = "DetachVolumeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DetachVolumeResponseType> asyncHandler);

    /**
     * 
     * @param detachVolumeRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DetachVolumeResponseType
     */
    @WebMethod(operationName = "DetachVolume", action = "DetachVolume")
    @WebResult(name = "DetachVolumeResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DetachVolumeResponseMsgResp")
    public DetachVolumeResponseType detachVolume(
        @WebParam(name = "DetachVolume", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DetachVolumeRequestMsgReq")
        DetachVolumeType detachVolumeRequestMsgReq);

    /**
     * 
     * @param createKeyPairRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.CreateKeyPairResponseType>
     */
    @WebMethod(operationName = "CreateKeyPair", action = "CreateKeyPair")
    public Response<CreateKeyPairResponseType> createKeyPairAsync(
        @WebParam(name = "CreateKeyPair", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateKeyPairRequestMsgReq")
        CreateKeyPairType createKeyPairRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param createKeyPairRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CreateKeyPair", action = "CreateKeyPair")
    public Future<?> createKeyPairAsync(
        @WebParam(name = "CreateKeyPair", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateKeyPairRequestMsgReq")
        CreateKeyPairType createKeyPairRequestMsgReq,
        @WebParam(name = "CreateKeyPairResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CreateKeyPairResponseType> asyncHandler);

    /**
     * 
     * @param createKeyPairRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.CreateKeyPairResponseType
     */
    @WebMethod(operationName = "CreateKeyPair", action = "CreateKeyPair")
    @WebResult(name = "CreateKeyPairResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateKeyPairResponseMsgResp")
    public CreateKeyPairResponseType createKeyPair(
        @WebParam(name = "CreateKeyPair", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "CreateKeyPairRequestMsgReq")
        CreateKeyPairType createKeyPairRequestMsgReq);

    /**
     * 
     * @param deleteKeyPairRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DeleteKeyPairResponseType>
     */
    @WebMethod(operationName = "DeleteKeyPair", action = "DeleteKeyPair")
    public Response<DeleteKeyPairResponseType> deleteKeyPairAsync(
        @WebParam(name = "DeleteKeyPair", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteKeyPairRequestMsgReq")
        DeleteKeyPairType deleteKeyPairRequestMsgReq);

    /**
     * 
     * @param asyncHandler
     * @param deleteKeyPairRequestMsgReq
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteKeyPair", action = "DeleteKeyPair")
    public Future<?> deleteKeyPairAsync(
        @WebParam(name = "DeleteKeyPair", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteKeyPairRequestMsgReq")
        DeleteKeyPairType deleteKeyPairRequestMsgReq,
        @WebParam(name = "DeleteKeyPairResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteKeyPairResponseType> asyncHandler);

    /**
     * 
     * @param deleteKeyPairRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DeleteKeyPairResponseType
     */
    @WebMethod(operationName = "DeleteKeyPair", action = "DeleteKeyPair")
    @WebResult(name = "DeleteKeyPairResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteKeyPairResponseMsgResp")
    public DeleteKeyPairResponseType deleteKeyPair(
        @WebParam(name = "DeleteKeyPair", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DeleteKeyPairRequestMsgReq")
        DeleteKeyPairType deleteKeyPairRequestMsgReq);

    /**
     * 
     * @param describeKeyPairsRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DescribeKeyPairsResponseType>
     */
    @WebMethod(operationName = "DescribeKeyPairs", action = "DescribeKeyPairs")
    public Response<DescribeKeyPairsResponseType> describeKeyPairsAsync(
        @WebParam(name = "DescribeKeyPairs", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeKeyPairsRequestMsgReq")
        DescribeKeyPairsType describeKeyPairsRequestMsgReq);

    /**
     * 
     * @param describeKeyPairsRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DescribeKeyPairs", action = "DescribeKeyPairs")
    public Future<?> describeKeyPairsAsync(
        @WebParam(name = "DescribeKeyPairs", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeKeyPairsRequestMsgReq")
        DescribeKeyPairsType describeKeyPairsRequestMsgReq,
        @WebParam(name = "DescribeKeyPairsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DescribeKeyPairsResponseType> asyncHandler);

    /**
     * 
     * @param describeKeyPairsRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DescribeKeyPairsResponseType
     */
    @WebMethod(operationName = "DescribeKeyPairs", action = "DescribeKeyPairs")
    @WebResult(name = "DescribeKeyPairsResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeKeyPairsResponseMsgResp")
    public DescribeKeyPairsResponseType describeKeyPairs(
        @WebParam(name = "DescribeKeyPairs", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeKeyPairsRequestMsgReq")
        DescribeKeyPairsType describeKeyPairsRequestMsgReq);

    /**
     * 
     * @param describeImagesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DescribeImagesResponseType>
     */
    @WebMethod(operationName = "DescribeImages", action = "DescribeImages")
    public Response<DescribeImagesResponseType> describeImagesAsync(
        @WebParam(name = "DescribeImages", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeImagesRequestMsgReq")
        DescribeImagesType describeImagesRequestMsgReq);

    /**
     * 
     * @param describeImagesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DescribeImages", action = "DescribeImages")
    public Future<?> describeImagesAsync(
        @WebParam(name = "DescribeImages", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeImagesRequestMsgReq")
        DescribeImagesType describeImagesRequestMsgReq,
        @WebParam(name = "DescribeImagesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DescribeImagesResponseType> asyncHandler);

    /**
     * 
     * @param describeImagesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DescribeImagesResponseType
     */
    @WebMethod(operationName = "DescribeImages", action = "DescribeImages")
    @WebResult(name = "DescribeImagesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeImagesRequestMsgResp")
    public DescribeImagesResponseType describeImages(
        @WebParam(name = "DescribeImages", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeImagesRequestMsgReq")
        DescribeImagesType describeImagesRequestMsgReq);

    /**
     * 
     * @param describeAvailabilityZonesRequestMsgReq
     * @return
     *     returns javax.xml.ws.Response<jp.primecloud.auto.nifty.soap.jaxws.DescribeAvailabilityZonesResponseType>
     */
    @WebMethod(operationName = "DescribeAvailabilityZones", action = "DescribeAvailabilityZones")
    public Response<DescribeAvailabilityZonesResponseType> describeAvailabilityZonesAsync(
        @WebParam(name = "DescribeAvailabilityZones", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeAvailabilityZonesRequestMsgReq")
        DescribeAvailabilityZonesType describeAvailabilityZonesRequestMsgReq);

    /**
     * 
     * @param describeAvailabilityZonesRequestMsgReq
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DescribeAvailabilityZones", action = "DescribeAvailabilityZones")
    public Future<?> describeAvailabilityZonesAsync(
        @WebParam(name = "DescribeAvailabilityZones", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeAvailabilityZonesRequestMsgReq")
        DescribeAvailabilityZonesType describeAvailabilityZonesRequestMsgReq,
        @WebParam(name = "DescribeAvailabilityZonesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DescribeAvailabilityZonesResponseType> asyncHandler);

    /**
     * 
     * @param describeAvailabilityZonesRequestMsgReq
     * @return
     *     returns jp.primecloud.auto.nifty.soap.jaxws.DescribeAvailabilityZonesResponseType
     */
    @WebMethod(operationName = "DescribeAvailabilityZones", action = "DescribeAvailabilityZones")
    @WebResult(name = "DescribeAvailabilityZonesResponse", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeAvailabilityZonesRequestMsgResp")
    public DescribeAvailabilityZonesResponseType describeAvailabilityZones(
        @WebParam(name = "DescribeAvailabilityZones", targetNamespace = "https://cp.cloud.nifty.com/api/1.3/", partName = "DescribeAvailabilityZonesRequestMsgReq")
        DescribeAvailabilityZonesType describeAvailabilityZonesRequestMsgReq);

}
