#!/bin/bash

DIR=$(cd $(dirname "$0") && pwd)

TTY=`ps | grep -v "grep" | grep -m 1 "init.sh" | awk '{print $2}'`
SOURCE=`who | grep "${TTY}" | awk '{print $NF}'`
LAST=`expr ${#SOURCE} - 1`
SOURCE_IP=`echo "${SOURCE}" | cut -c2-${LAST}`

REPO_URL=http://repo.primecloud.jp/repository

# instancedata
echo "$1" > /root/instancedata

# yum
#cp -p $DIR/init/adc.repo /etc/yum.repos.d/adc.repo
rpm -ivh http://ftp.riken.jp/Linux/fedora/epel/5/x86_64/epel-release-5-4.noarch.rpm
rpm -ivh http://repo.zabbix.jp/relatedpkgs/rhel5/x86_64/zabbix-jp-release-5-6.noarch.rpm
sed -i -e "s/enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
yum --enablerepo=epel -y update epel-release
#wget -q --connect-timeout=30 --tries=4 --spider ${REPO_URL}/adc.repo
#if [ $? = 0 ]; then
#    wget --tries=4 -O /etc/yum.repos.d/adc.repo ${REPO_URL}/adc.repo
#fi

# init
cp -p $DIR/init/host-init.sh.nifty /etc/init.d/host-init.sh
chmod a+x /etc/init.d/host-init.sh
ln -s /etc/init.d/host-init.sh /etc/rc3.d/S90host-init
ln -s /etc/init.d/host-init.sh /etc/rc4.d/S90host-init
ln -s /etc/init.d/host-init.sh /etc/rc5.d/S90host-init
mkdir /root/script
cp -p $DIR/init/init.sh /root/script/init.sh
chmod a+x /root/script/init.sh

# Network
echo "PEERDNS=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
echo "PEERDNS=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
chkconfig named off
mv /etc/sysconfig/iptables /etc/sysconfig/iptables.org
sed -e "s/-A RH-Firewall-1-INPUT -m tcp -p tcp --dport 22 -j ACCEPT/-A RH-Firewall-1-INPUT -m tcp -p tcp -s ${SOURCE_IP} --dport 22 -j ACCEPT\\n-A RH-Firewall-1-INPUT -p all -i tun0 -j ACCEPT\\n#generated by controller start\\n## DO NOT EDIT !!!!\\n## DO NOT EDIT !!!!\\n#generated by controller stop/g" /etc/sysconfig/iptables.org > /etc/sysconfig/iptables

# Puppet
yum install -y ruby-rdoc
yum localinstall -y /tmp/image/puppet/facter-1.6.6-1.el5.noarch.rpm /tmp/image/puppet/puppet-2.7.17-1.el5.noarch.rpm --nogpgcheck --enablerepo=epel
echo 'PUPPET_EXTRA_OPTS="--waitforcert=120 --no-client --verbose"' >> /etc/sysconfig/puppet
mv /etc/puppet/puppet.conf /etc/puppet/puppet.conf.org
cp -p $DIR/puppet/puppet.conf /etc/puppet/puppet.conf
cp -p $DIR/puppet/namespaceauth.conf /etc/puppet/namespaceauth.conf
cp -p $DIR/puppet/auth.conf /etc/puppet/auth.conf
chkconfig puppet on

# Zabbix
yum install -y OpenIPMI-libs gnutls
yum install -y --enablerepo=epel fping iksemel
yum install -y zabbix zabbix-agent
chkconfig zabbix-agent off

# ntp
yum install --enablerepo=epel -y ntp
chkconfig ntpd off

# rsyslog
yum install --enablerepo=epel -y rsyslog
chkconfig rsyslog on
chkconfig syslog off
mv /etc/rsyslog.conf /etc/rsyslog.conf.org
cp -p $DIR/rsyslog/rsyslog.conf /etc/rsyslog.conf
mv /etc/sysconfig/rsyslog /etc/sysconfig/rsyslog.org
cp -p $DIR/rsyslog/rsyslog /etc/sysconfig/rsyslog
rm -f /etc/logrotate.d/syslog
cp -p $DIR/rsyslog/syslog /etc/logrotate.d/syslog

# OpenVPN
yum install -y expect zip unzip
yum install -y --enablerepo=epel openvpn
chkconfig openvpn off
#chkconfig haldaemon off
mkdir /etc/openvpn/zip
cp -p $DIR/openvpn/client.zip /etc/openvpn/zip/client.zip

# ssh
usermod -p '*' root
rm -f /etc/ssh/sshd_config
cp -p $DIR/ssh/sshd_config /etc/ssh/sshd_config


# Apache
yum install --enablerepo=epel -y httpd mod_ssl
chkconfig httpd off
groupadd -g 200 webmaster
rmdir /var/log/httpd/

# MySQL
yum install --enablerepo=epel -y mysql-server
chkconfig mysqld off

# Java
#wget --tries=4 -O /tmp/jdk-6u21-linux-x64-rpm.bin ${REPO_URL}/other/jdk-6u21-linux-x64-rpm.bin
cp -p $DIR/init/jdk-6u45-linux-x64-rpm.bin /tmp
chmod a+x /tmp/jdk-6u45-linux-x64-rpm.bin
expect -c "
set timeout -1
spawn /tmp/jdk-6u45-linux-x64-rpm.bin
expect \"Press Enter to continue.....\"
send \n
expect \"Done.\"
interact"
rm jdk*.rpm sun-javadb*.rpm -f

# Geronimo
groupadd -g 500 geronimo
useradd -g 500 -u 500 geronimo -s /sbin/nologin
mkdir /var/run/geronimo
chown geronimo:geronimo /var/run/geronimo/
cp -p $DIR/geronimo/geronimo /etc/init.d/geronimo
chmod a+x /etc/init.d/geronimo
chkconfig --add geronimo
chkconfig geronimo off

# Tomcat
groupadd -g 104 tomcat
useradd -d /opt/tomcat -s /sbin/nologin -M -u 104 -g 104 tomcat
mkdir /var/run/tomcat
chown tomcat:tomcat /var/run/tomcat/
cp -p $DIR/tomcat/tomcat /etc/init.d/tomcat
chmod a+x /etc/init.d/tomcat
chkconfig --add tomcat
chkconfig tomcat off

# lighttpd
yum install -y --enablerepo=epel lighttpd lighttpd-fastcgi
chkconfig lighttpd off
mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.org
cp -p $DIR/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf
mv /srv/www/lighttpd /var/
rmdir /srv/www/
rmdir /srv/
mkdir /var/run/lighttpd
chown lighttpd:lighttpd /var/run/lighttpd/
usermod -G apache lighttpd

# phpMyAdmin
wget http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.2-2.el5.rf.x86_64.rpm
rpm --import http://apt.sw.be/RPM-GPG-KEY.dag.txt
rpm -ivh rpmforge-release-0.5.2-2.el5.rf.x86_64.rpm
sed -i -e "s/enabled=1/enabled=0/" /etc/yum.repos.d/rpmforge.repo
yum install --enablerepo=epel -y php php-mbstring php-mcrypt php-pear-DB php-mysql
yum install -y --enablerepo=rpmforge phpmyadmin
if [ -e /usr/share/phpMyAdmin ]; then
   mv /usr/share/phpMyAdmin /usr/share/phpmyadmin
fi
ln -s /usr/share/phpmyadmin /var/lighttpd/phpmyadmin
rm -f /usr/share/phpmyadmin/config.inc.php
cp -p $DIR/phpmyadmin/config.inc.php /usr/share/phpmyadmin/
chown root:apache /usr/share/phpmyadmin/config.inc.php
chmod 640 /usr/share/phpmyadmin/config.inc.php
rm -f /etc/httpd/conf.d/phpmyadmin.conf

yum clean all
