DROP TABLE IF EXISTS EVENT_LOG;

CREATE TABLE EVENT_LOG(
	LOG_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
	LOG_DATE DATETIME NOT NULL,
	LOG_LEVEL SMALLINT,
	USER_NO BIGINT ,
	USER_NAME VARCHAR(100),
	FARM_NO BIGINT ,
	FARM_NAME VARCHAR(100),
	COMPONENT_NO BIGINT ,
	COMPONENT_NAME VARCHAR(100),
	INSTANCE_NO BIGINT ,
	INSTANCE_NAME VARCHAR(100),
	MESSAGE_CODE VARCHAR(100) NOT NULL,
	MESSAGE VARCHAR(1000) NOT NULL,
	INSTANCE_TYPE VARCHAR(30),
	PLATFORM_NO BIGINT
);

ALTER TABLE EVENT_LOG ADD INDEX INDEX_LOG_DATE_USER_NO(LOG_DATE,USER_NO);



