DROP TABLE IF EXISTS OPERATION_LOG;

CREATE TABLE OPERATION_LOG(
	O_LOG_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
	O_LOG_DATE DATETIME NOT NULL,
	USER_NO BIGINT ,
	USER_NAME VARCHAR(100),
	SCREEN VARCHAR(100),
	OPERATION VARCHAR(100),
	FARM_NO BIGINT ,
	INSTANCE_NO BIGINT ,
	COMPONENT_NO BIGINT ,
	LOAD_BALANCER_NO BIGINT ,
	MEMO VARCHAR(300)
);

ALTER TABLE OPERATION_LOG ADD INDEX INDEX_O_LOG_DATE_USER_NO(O_LOG_DATE,USER_NO);

