#!/bin/sh
#
# chkconfig: 345 85 15
# description: Tomcat
#

. /etc/rc.d/init.d/functions

[ -f /etc/sysconfig/tomcat ] && . /etc/sysconfig/tomcat

prog=tomcat

JAVA_HOME=/usr/java/default
CATALINA_HOME=/opt/tomcat/default
PID_FILE=/var/run/tomcat/${prog}.pid
LOCK_FILE=/var/lock/subsys/${prog}
USER=tomcat

#CATALINA_OPTS="-Xms512m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m"
CATALINA_OPTS="-Xms512m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -Dsun.net.inetaddr.ttl=1 -Dsun.net.inetaddr.negative.ttl=0"
#DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"
CATALINA_OPTS="${CATALINA_OPTS} ${DEBUG_OPTS}"


startup() {
    COMMAND="export JAVA_HOME=${JAVA_HOME}"
    COMMAND="${COMMAND};export CATALINA_HOME=${CATALINA_HOME}"
    COMMAND="${COMMAND};export CATALINA_PID=${PID_FILE}"
    COMMAND="${COMMAND};export CATALINA_OPTS=\"${CATALINA_OPTS}\""

    COMMAND="${COMMAND};${CATALINA_HOME}/bin/catalina.sh start"

    su -s /bin/bash - ${USER} -c "${COMMAND}"

    RETVAL=$?

    if [ $RETVAL = 0 ]; then
        touch ${LOCK_FILE}
        action $"Starting $prog: " /bin/true
    else
        action $"Starting $prog: " /bin/false
    fi

    return $RETVAL
}

shutdown() {
    COMMAND="export JAVA_HOME=${JAVA_HOME}"
    COMMAND="${COMMAND};export CATALINA_HOME=${CATALINA_HOME}"
    COMMAND="${COMMAND};export CATALINA_PID=${PID_FILE}"

    COMMAND="${COMMAND};${CATALINA_HOME}/bin/catalina.sh stop"

    su -s /bin/bash - ${USER} -c "${COMMAND}"

    RETVAL=$?

    if [ -e "${PID_FILE}" ]; then
        PID=`cat ${PID_FILE}`
        if [ -n "`ps -e | grep ${PID}`" ]; then
            kill -9 ${PID}
        fi
        rm -f ${PID_FILE}
    fi
    if [ -e "${LOCK_FILE}" ]; then
        rm -f ${LOCK_FILE}
    fi

    if [ $RETVAL = 0 ]; then
        action $"Stopping $prog: " /bin/true
    else
        action $"Stopping $prog: " /bin/false
    fi

    return $RETVAL
}


case "$1" in
    start)
        startup
        ;;
    stop)
        shutdown
        ;;
    restart)
        shutdown
        startup
        ;;
    status)
        status -p ${PID_FILE} ${prog}
        RETVAL=$?
        ;;
    *)
        echo $"Usage: ${prog} {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL

