alter table COMPONENT_LOAD_BALANCER add constraint COMPONENT_LOAD_BALANCER_FK1 foreign key (LOAD_BALANCER_NO) references LOAD_BALANCER (LOAD_BALANCER_NO);
alter table COMPONENT_LOAD_BALANCER add constraint COMPONENT_LOAD_BALANCER_FK2 foreign key (COMPONENT_NO) references COMPONENT (COMPONENT_NO);
