ALTER TABLE VCLOUD_DISK ADD CONSTRAINT VCLOUD_DISK_FK1 FOREIGN KEY (FARM_NO) REFERENCES FARM (FARM_NO);
ALTER TABLE VCLOUD_DISK ADD CONSTRAINT VCLOUD_DISK_FK2 FOREIGN KEY (COMPONENT_NO) REFERENCES COMPONENT (COMPONENT_NO);
ALTER TABLE VCLOUD_DISK ADD CONSTRAINT VCLOUD_DISK_FK3 FOREIGN KEY (INSTANCE_NO) REFERENCES VCLOUD_INSTANCE (INSTANCE_NO);
ALTER TABLE VCLOUD_DISK ADD CONSTRAINT VCLOUD_DISK_FK4 FOREIGN KEY (PLATFORM_NO) REFERENCES PLATFORM (PLATFORM_NO);