ALTER TABLE VCLOUD_INSTANCE_NETWORK ADD CONSTRAINT VCLOUD_INSTANCE_NETWORK_FK1 FOREIGN KEY (PLATFORM_NO) REFERENCES PLATFORM (PLATFORM_NO);
ALTER TABLE VCLOUD_INSTANCE_NETWORK ADD CONSTRAINT VCLOUD_INSTANCE_NETWORK_FK2 FOREIGN KEY (INSTANCE_NO) REFERENCES INSTANCE (INSTANCE_NO);
ALTER TABLE VCLOUD_INSTANCE_NETWORK ADD CONSTRAINT VCLOUD_INSTANCE_NETWORK_FK3 FOREIGN KEY (FARM_NO) REFERENCES FARM (FARM_NO);
