ALTER TABLE VCLOUD_INSTANCE ADD CONSTRAINT VCLOUD_INSTANCE_FK1 FOREIGN KEY (INSTANCE_NO) REFERENCES INSTANCE (INSTANCE_NO);
ALTER TABLE VCLOUD_INSTANCE ADD CONSTRAINT VCLOUD_INSTANCE_FK2 FOREIGN KEY (KEY_PAIR_NO) REFERENCES VCLOUD_KEY_PAIR (KEY_NO);
ALTER TABLE VCLOUD_INSTANCE ADD CONSTRAINT VCLOUD_INSTANCE_FK3 FOREIGN KEY (STORAGE_TYPE_NO) REFERENCES PLATFORM_VCLOUD_STORAGE_TYPE (STORAGE_TYPE_NO);
