CREATE TABLE IMAGE_VCLOUD (
    IMAGE_NO BIGINT(20) NOT NULL,
    TEMPLATE_NAME VARCHAR(100) NOT NULL,
    INSTANCE_TYPES VARCHAR(500) NOT NULL,
    CONSTRAINT IMAGE_VCLOUD_PK PRIMARY KEY (IMAGE_NO)
);