CREATE TABLE PLATFORM_VCLOUD_STORAGE_TYPE (
    STORAGE_TYPE_NO BIGINT(20) NOT NULL AUTO_INCREMENT,
    PLATFORM_NO BIGINT(20) NOT NULL,
    STORAGE_TYPE_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PLATFORM_VCLOUD_STORAGE_TYPE_PK1 PRIMARY KEY (STORAGE_TYPE_NO)
);