CREATE TABLE VCLOUD_CERTIFICATE (
    USER_NO BIGINT NOT NULL,
    PLATFORM_NO BIGINT NOT NULL,
    VCLOUD_ACCESS_ID VARCHAR(100) NOT NULL,
    VCLOUD_SECRET_KEY VARCHAR(100) NOT NULL,
    CONSTRAINT VCLOUD_CERTIFICATE_PK PRIMARY KEY (USER_NO, PLATFORM_NO)
);