CREATE TABLE VCLOUD_DISK (
    DISK_NO BIGINT NOT NULL AUTO_INCREMENT,
    DISK_ID VARCHAR(20),
    FARM_NO BIGINT NOT NULL,
    PLATFORM_NO BIGINT NOT NULL,
    COMPONENT_NO BIGINT,
    INSTANCE_NO BIGINT,
    SIZE INT,
    UNIT_NO INT,
    ATTACHED BOOLEAN,
    DATA_DISK BOOLEAN NOT NULL,
    CONSTRAINT VCLOUD_DISK_PK PRIMARY KEY(DISK_NO)
);
