CREATE TABLE VCLOUD_INSTANCE (
    INSTANCE_NO BIGINT NOT NULL,
    VM_NAME VARCHAR(100),
    STORAGE_TYPE_NO BIGINT,
    INSTANCE_TYPE VARCHAR(30),
    KEY_PAIR_NO BIGINT,
    STATUS VARCHAR(20),
    IP_ADDRESS VARCHAR(100),
    PRIVATE_IP_ADDRESS VARCHAR(100),
    CONSTRAINT VCLOUD_INSTANCE_PK PRIMARY KEY(INSTANCE_NO)
);
