CREATE TABLE VCLOUD_INSTANCE_NETWORK (
    NETWORK_NO BIGINT NOT NULL AUTO_INCREMENT,
    PLATFORM_NO BIGINT NOT NULL,
    INSTANCE_NO BIGINT NOT NULL,
    FARM_NO BIGINT NOT NULL,
    NETWORK_NAME varchar(100) NOT NULL,
    NETWORK_INDEX INT,
    IP_MODE VARCHAR(100) NOT NULL,
    IP_ADDRESS VARCHAR(100),
    IS_PRIMARY BOOLEAN NOT NULL,
    CONSTRAINT VCLOUD_NETWORK_PK PRIMARY KEY(NETWORK_NO)
);
