#!/bin/bash

START=`grep -n '\#generated by controller start' /etc/sysconfig/iptables | awk -F : '{print $1}'`
STOP=`grep -n '\#generated by controller stop' /etc/sysconfig/iptables | awk -F : '{print $1}'`
COUNT=`wc -l /etc/sysconfig/iptables | awk '{print $1}'`

if [ -z "$START" ]; then
    exit 1
fi

if [ -z "$STOP" ]; then
    exit 1
fi

head -n $START /etc/sysconfig/iptables > /tmp/iptables

echo "## DO NOT EDIT !!!!" >> /tmp/iptables

IPLIST=$1
while [ -n "$IPLIST" ]
do
    IP=`echo "$IPLIST" | cut -d "," -f 1`
    echo "-A RH-Firewall-1-INPUT -p all -s $IP -j ACCEPT" >> /tmp/iptables

    IPLIST=`echo "$IPLIST" | cut -d "," -f 2-`
    if [ "$IP" = "$IPLIST" ]; then
        break
    fi
done

echo "## DO NOT EDIT !!!!" >> /tmp/iptables

tail -n `expr $COUNT - $STOP + 1` /etc/sysconfig/iptables >> /tmp/iptables

mv -f /tmp/iptables /etc/sysconfig/iptables
