INSERT INTO COMPONENT_TYPE (COMPONENT_TYPE_NO, COMPONENT_TYPE_NAME, COMPONENT_TYPE_NAME_DISP, LAYER, LAYER_DISP, RUN_ORDER, ZABBIX_TEMPLATE, SELECTABLE) VALUES (1, 'mysql','MySQL Community Server','db','データベースサーバ',100,'Template_MW_MySQL',1);
INSERT INTO COMPONENT_TYPE (COMPONENT_TYPE_NO, COMPONENT_TYPE_NAME, COMPONENT_TYPE_NAME_DISP, LAYER, LAYER_DISP, RUN_ORDER, ZABBIX_TEMPLATE, SELECTABLE) VALUES (2, 'tomcat','Apache Tomcat','ap_java','Java EEサーバ',200,'Template_MW_Tomcat',1);
INSERT INTO COMPONENT_TYPE (COMPONENT_TYPE_NO, COMPONENT_TYPE_NAME, COMPONENT_TYPE_NAME_DISP, LAYER, LAYER_DISP, RUN_ORDER, ZABBIX_TEMPLATE, SELECTABLE) VALUES (4, 'apache','Apache HTTP Server','web','Webサーバ',300,'Template_MW_Apache',1);
INSERT INTO COMPONENT_TYPE (COMPONENT_TYPE_NO, COMPONENT_TYPE_NAME, COMPONENT_TYPE_NAME_DISP, LAYER, LAYER_DISP, RUN_ORDER, ZABBIX_TEMPLATE, SELECTABLE) VALUES (5, 'ultramonkey','','lb','',400,'Template_LB_UltraMonkey',1);
INSERT INTO COMPONENT_TYPE (COMPONENT_TYPE_NO, COMPONENT_TYPE_NAME, COMPONENT_TYPE_NAME_DISP, LAYER, LAYER_DISP, RUN_ORDER, ZABBIX_TEMPLATE, SELECTABLE) VALUES (8, 'windows','Windows Server','windows','Windows Server',1500,NULL,1);

