#!/bin/sh
#
# geronimo    Apache Geronimo
#
# chkconfig: 2345 80 20
# description: Apache Geronimo

# Source function library.
. /etc/rc.d/init.d/functions

[ -f /etc/sysconfig/geronimo ] && . /etc/sysconfig/geronimo
EXECUTE_USER=geronimo
JAVA_HOME=/usr/java/jdk1.5.0_19

##GERONIMO_HOME=/opt/geronimo/default
##GERONIMO_USER=system
##GERONIMO_PASSWORD=manager
##GERONIMO_OPTS="-Xms512m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"


RETVAL=0
GERONIMO_PID="/var/run/geronimo/geronimo.pid"

# Geronimoを起動する。
startup() {
    if status -p $GERONIMO_PID > /dev/null; then
        echo -n $"geronimo: already running"
        failure
        echo
        return 1
    fi

    export JAVA_HOME=$JAVA_HOME
    export GERONIMO_OPTS=$GERONIMO_OPTS
    export GERONIMO_PID=$GERONIMO_PID

    $GERONIMO_HOME/bin/startup.sh
    RETVAL=$? 
    return $RETVAL
}


# Geronimoを停止する。
shutdown() {
    export JAVA_HOME=$JAVA_HOME
    export GERONIMO_PID=$GERONIMO_PID
    
    $GERONIMO_HOME/bin/shutdown.sh --user $GERONIMO_USER --password $GERONIMO_PASSWORD
    RETVAL=$?

    if [ -e "$GERONIMO_PID" ]; then
        PID=`cat $GERONIMO_PID`
        if [ -n "`ps -e | grep $PID`" ]; then
            kill -9 $PID
        fi
        rm -f $GERONIMO_PID
    fi
    return $RETVAL
}


# スクリプトの実行ユーザをチェックし、
# rootであればGeronimo実行ユーザに変わって再実行する。
# rootでもGeronimo実行ユーザでもない場合は、エラーとして終了する。

if [ -z $USER ] || [ $USER = root ]; then
    SCRIPT=$(cd $(dirname "$0") && pwd)/$(basename "$0")
    COMMAND="$SCRIPT $@"
    su -s /bin/bash - $EXECUTE_USER -c "$COMMAND"
    RETVAL=$?
    exit $RETVAL

elif [ $USER != $EXECUTE_USER ]; then
    echo "This script must be executed by 'root' or '$EXECUTE_USER'."
    exit 1

fi


# スクリプトの引数に応じてGeronimoを起動、停止、再起動する。
case "$1" in
    start)
        startup
        ;;
    stop)
        shutdown
        ;;
    restart)
        shutdown
        startup
        ;;
    status)
        status -p $GERONIMO_PID
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL


